- name: install required system packages
  become: yes
  apt: 
    name: "{{ item }} "
    state: latest 
    update_cache: yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: add docker GPG apt key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: update apt and install docker-ce
  become: yes
  apt: 
    update_cache: yes 
    name: docker-ce 
    state: latest

- name: download current stable docker-compose
  become: yes
  shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: install docker-compose
  become: yes
  shell: chmod +x /usr/local/bin/docker-compose