- name: create pqs dir
  become: yes
  file:
    path: /aquila-pqs/
    state: directory
    mode: '0777'
    recurse: yes

- name: docker-compose
  template: 
    src: docker-compose.j2
    dest: /aquila-pqs/docker-compose.yml
