---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: shared-certs
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: infra@aqilliz.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
        - "*.staging.aqilliz.com"
      dns01:
        route53:
          region: ap-south-1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: shared-certs
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: infra@aqilliz.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
        - "*.staging.aqilliz.com"
      dns01:
        route53:
          region: ap-south-1
