- name: authenticate docker ecr
  shell: aws ecr-public get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin public.ecr.aws

- name: pull aquila substrate image
  become: yes
  shell: docker pull {{ aquila_image }}